sudo: required

services:
  - docker
jobs:
  include:
    - language: java
      jdk: openjdk17
      name: Java Service Build

      before_install:
        - docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" https://europe-west2-docker.pkg.dev;
        - docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}";
        - docker network create ssdcrmdockerdev_default
        - echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > ~/google-service-account-key.json
        - export GOOGLE_APPLICATION_CREDENTIALS=~/google-service-account-key.json
        - make check-mvn

      install: echo "SKIPPING DEFAULT INSTALL" # Travis has a default maven install. Don't build twice!

      script: travis_wait mvn verify jacoco:report

      after_success:
        - gpg --no-default-keyring --keyring trustedkeys.gpg --import codecov_public_key.asc
        - curl -Os https://uploader.codecov.io/latest/linux/codecov
        - curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
        - curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig

        # NOTE: the "|| exit 1"'s are required to stop travis continuing to run subsequent steps even if the integrity checks failed
        - gpgv codecov.SHA256SUM.sig codecov.SHA256SUM || exit 1
        - shasum -a 256 -c codecov.SHA256SUM || exit 1

        - chmod +x codecov
        - ./codecov

      cache:
        directories:
          - $HOME/.m2

    - language: node_js
      node_js: 14
      name: UI Checks

      before_install:
        - make format-check-ui
        - make package-audit-ui

      script: echo "SKIPPING DEFAULT SCRIPT" # Travis has a default node script step we do not want to run

branches:
  only:
    - main
