sudo: required

services:
  - docker
jobs:
  include:
    - language: java
      jdk: openjdk11

      before_install:
        - make format-check-mvn

      install: echo "SKIPPING DEFAULT INSTALL" # Travis has a default maven install. Don't build twice!

      script: travis_wait mvn verify jacoco:report

      after_success:
        - bash <(curl -s https://codecov.io/bash)

      cache:
        directories:
          - $HOME/.m2

    - language: node_js
      node_js: 14

      before_install:
        - make format-check-ui

      script: echo "SKIPPING DEFAULT SCRIPT" # Travis has a default node script step we do not want to run

branches:
  only:
    - main