server:
  port: 9999

info:
  app:
    name: Support Tool
    version: 1.0

spring:
  data:
    rest:
      base-path: /api

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres?readOnly=true
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          batch_size: 500
          order_inserts: true
          lob:
            non_contextual_creation: true

  task:
    scheduling:
      pool:
        size: 10

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

iapaudience: DUMMY

# TODO: Remove this before releasing to prod
dummyuseridentity: dummy@fake-email.com

printsupplierconfig: '{"SUPPLIER_A":{"sftpDirectory":"foo","encryptionKeyFilename": "bar"},"SUPPLIER_B":{"sftpDirectory":"foo","encryptionKeyFilename":"bar"}}'

queueconfig:
  sample-topic: rm-internal-sample
  fulfilment-topic: event_paper-fulfilment
  deactivate-uac-topic: event_deactivate-uac
  refusal-event-topic: event_refusal
  invalid-case-event-topic: event_invalid-case
  update-sample-sensitive-topic: event_update-sample-sensitive
  publishtimeout: 30  # In seconds

file-upload-storage-path: /tmp/