server:
  port: 9999

info:
  app:
    name: Support Tool
    version: 1.0

spring:
  data:
    rest:
      base-path: /api

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres?readOnly=true
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          batch_size: 500
          order_inserts: true
          lob:
            non_contextual_creation: true

  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8538
        project-id: project

  task:
    scheduling:
      pool:
        size: 10

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

iapaudience: DUMMY

# TODO: Remove this before releasing to prod
dummyuseridentity: dummy@fake-email.com

printsupplierconfig: '{"SUPPLIER_A":{"sftpDirectory":"foo","encryptionKeyFilename": "bar"},"SUPPLIER_B":{"sftpDirectory":"foo","encryptionKeyFilename":"bar"}}'

queueconfig:
  sample-topic: supportTool.caseProcessor.sample.topic
  fulfilment-topic: events.caseProcessor.fulfilment.topic
  deactivate-uac-topic: events.caseProcessor.deactivateUac.topic
  refusal-event-topic: events.caseProcessor.refusal.topic
  invalid-address-event-topic: events.caseProcessor.invalidAddress.topic
  publishtimeout: 30  # In seconds

file-upload-storage-path: /tmp/