server:
  port: 9999

info:
  app:
    name: Support Tool
    version: 1.0

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres?readOnly=true
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          batch_size: 500
          order_inserts: true
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

  task:
    scheduling:
      pool:
        size: 10

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  metrics:
    tags:
      application: Support Tool
      pod: ${HOSTNAME}
    export:
      stackdriver:
        project-id: dummy-project-id
        enabled: false
        step: PT1M

iapaudience: DUMMY

printsupplierconfig: '{"SUP_A":{"sftpDirectory":"foo","encryptionKeyFilename": "bar"},"SUP_B":{"sftpDirectory":"foo","encryptionKeyFilename":"bar"},"SUP_C":{"sftpDirectory":"foo","encryptionKeyFilename":"bar"}}'