server:
  port: 9999

info:
  app:
    name: Support Tool
    version: 1.0

spring:
  data:
    rest:
      base-path: /api

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres?readOnly=true
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          batch_size: 500
          order_inserts: true
          lob:
            non_contextual_creation: true
  task:
    scheduling:
      pool:
        size: 10

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  profile: DEV
  level:
    root: INFO

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  health:
    pubsub:
      enabled: false
  metrics:
    tags:
      application: Support Tool
      pod: ${HOSTNAME}
    export:
      stackdriver:
        project-id: dummy-project-id
        enabled: false
        step: PT1M

notifyservice:
  connection:
    scheme: http
    host: localhost
    port: 8162

# false FOR TESTING ONLY, REMOVE ENTIRELY WHENN COMMITTING
iapaudience: false

exportfiledestinationconfigfile: dummy-export-file-destination-config.json

queueconfig:
  new-case-topic: event_new-case
  print-fulfilment-topic: event_print-fulfilment
  deactivate-uac-topic: event_deactivate-uac
  refusal-event-topic: event_refusal
  invalid-case-event-topic: event_invalid-case
  update-sample-topic: event_update-sample
  update-sample-sensitive-topic: event_update-sample-sensitive
  survey-update-event-topic: event_survey-update
  collection-exercise-update-event-topic: event_collection-exercise-update
  publishtimeout: 30  # In seconds
  shared-pubsub-project: REPLACEME

file-upload-storage-path: /tmp/

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

ras-rm-sample-service:
  connection:
    scheme: http
    host: localhost
    port: 8125

CSP-upgrade-policy: "upgrade-insecure-requests;"
