spring:
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8538
        project-id: our-project

queueconfig:
  shared-pubsub-project: our-project

iap-enabled: false # This ** MUST ALWAYS!! ** be true in production!!!

