spring:
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8538
        project-id: our-project

queueconfig:
  shared-pubsub-project: shared-project

dummyuseridentity-allowed: true # This ** MUST ALWAYS!! ** be false in production!!!
