package uk.gov.ons.ssdc.supporttool.model.entity;

public enum EventType {
  CASE_CREATED,
  RESPONSE_RECEIVED,
  REFUSAL_RECEIVED,
  SURVEY_LAUNCHED,
  ADDRESS_NOT_VALID,
  RESPONDENT_AUTHENTICATED,
  TELEPHONE_CAPTURE_REQUESTED,
  FULFILMENT,
  PRINTED_PACK_CODE,
  DEACTIVATE_UAC,
  UPDATE_SAMPLE_SENSITIVE,
}
