package uk.gov.ons.ssdc.supporttool.model.entity;

public enum EventType {
  CASE_CREATED,
  UAC_UPDATED,
  RESPONSE_RECEIVED,
  REFUSAL_RECEIVED,
  SAMPLE_LOADED,
  RM_UAC_CREATED,
  SURVEY_LAUNCHED,
  ADDRESS_NOT_VALID,
  RESPONDENT_AUTHENTICATED,
  FULFILMENT,
  PRINTED_PACK_CODE,
}
